// One distinct badge per paid-member achievement; reused artwork keeps its original file.
export const ACHIEVEMENT_BADGES: Record<string, string> = {
  "첫 발걸음": "/badges/badge-2.png",
  "모험의 시작": "/badges/badge-6.png",
  "개척자": "/badges/badge-7.png",
  "업적 마스터": "/badges/badge-15.png",
  "준프로": "/badges/badge-9.png",
  "마스터": "/badges/badge-level-1000.png",
  "인맥의 시작": "/badges/badge-11.png",
  "소문난 인싸": "/badges/badge-12.png",
  "마당발": "/badges/badge-14.png",
  "추천회장": "/badges/badge-13.png",
  "다이아 클럽": "/badges/badge-8.png",
  "입금의 귀족": "/badges/badge-10.png",
  "연승의 신": "/badges/badge-1.png",
  "스포츠의 신": "/badges/badge-3.png",
  "잭팟의 왕": "/badges/badge-5.png",
  "미니게임 황제": "/badges/badge-4.png",
  "버그 헌터": "/badges/achievement-sng-bug-transparent-v3.png",
  "업적 도전자": "/badges/achievement-sng-ach3-transparent-v3.png",
  "업적 수집가": "/badges/achievement-sng-ach5-transparent-v3.png",
  "성실한 모험가": "/badges/achievement-sng-qst10-transparent-v3.png",
  "퀘스트 베테랑": "/badges/achievement-sng-qst30-transparent-v3.png",
  "미션 해결사": "/badges/achievement-sng-qst50-transparent-v3.png",
  "루키": "/badges/achievement-lvl-1-transparent-v3.png",
  "비기너": "/badges/achievement-lvl-100-transparent-v3.png",
  "프로": "/badges/achievement-lvl-500-transparent-v3.png",
  "추천의 제왕": "/badges/achievement-ref-10-transparent-v3.png",
  "실버 VIP": "/badges/achievement-dep-10m-transparent-v3.png",
  "골드 VIP": "/badges/achievement-dep-50m-transparent-v3.png",
  "금고의 주인": "/badges/achievement-dep-10b-transparent-v3.png",
  "짜릿한 승리자": "/badges/achievement-wth-1m-transparent-v3.png",
  "환전의 달인": "/badges/achievement-wth-50m-transparent-v3.png",
  "현금화의 마술사": "/badges/achievement-wth-1b-transparent-v3.png",
  "슈퍼리치": "/badges/achievement-wth-5b-transparent-v3.png",
  "출금의 마스터": "/badges/achievement-wth-10b-transparent-v3.png",
  "승리의 기세": "/badges/achievement-cas-3-transparent-v3.png",
  "하이롤러": "/badges/achievement-cas-5-transparent-v3.png",
  "황금의 손": "/badges/achievement-cas-7-transparent-v3.png",
  "승부 예측가": "/badges/achievement-spt-3-transparent-v3.png",
  "적중의 묘수": "/badges/achievement-spt-5-transparent-v3.png",
  "스포츠 전략가": "/badges/achievement-spt-6-transparent-v3.png",
  "빅토리 마스터": "/badges/achievement-spt-8-transparent-v3.png",
  "행운의 릴": "/badges/achievement-slt-100-transparent-v3.png",
  "스핀 매니아": "/badges/achievement-slt-500-transparent-v3.png",
  "메가 볼텍스": "/badges/achievement-slt-5k-transparent-v3.png",
  "슬롯의 신": "/badges/achievement-slt-10k-transparent-v3.png",
  "직관의 승부사": "/badges/achievement-mini-3-transparent-v3.png",
  "예측의 달인": "/badges/achievement-mini-5-transparent-v3.png",
  "확률의 지배자": "/badges/achievement-mini-7-transparent-v3.png"
};
